#!/usr/bin/env bash
# Displaying Bad luck for 4th loop iteration and good luck for 8th loop iteration
i=1
while [ "$i" -le 10 ]
do
  if [ "$i" -eq 4 ]
  then 
    echo "bad luck"
  elif [ "$i" -eq 8 ]
  then
    echo "good luck"
  else 
    echo "Best School"
  fi
  ((i+=1))    
done
