#!/usr/bin/env bash
# Main Controller
case $1 in
  start)
    ./manage_my_process $
sleep 1    
echo $! > /var/run/my_process.pid 
    echo "manage_my_process started"
  ;;
  stop)
    kill $(cat /var/run/my_process.pid)
    rm -f /var/run/my_process.pid
    echo "manage_my_process stopped"
  ;;
  restart)
    $0 stop
    echo "manage_my_process restarted"
    sleep 1
$0 start
  ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
  ;;
esac
