#!/usr/bin/env bash
# Main Controller
PROCESS="./manage_my_process"
PID_FILE="/var/run/my_process.pid"

case "$1" in
  start)
    $PROCESS &
    echo $! > "$PID_FILE"
    echo "manage_my_process started"
  ;;
  stop)
    kill "$(cat $PID_FILE)"
    rm -f "$PID_FILE"
    echo "manage_my_process stopped"
  ;;
  restart)
    $0 stop
    echo "manage_my_process restarted"
    sleep 1
    $0 start
  ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
  ;;
esac


